version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonarnet
    depends_on:
      - db
  
  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    - POSTGRES_DB=sonar
    networks:
      - sonarnet
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
  
  sonarscanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonarscanner
    volumes:
      - .:/usr/src
    networks:
      - sonarnet
    entrypoint: ["bash", "-c", "sonar-scanner -Dsonar.projectKey=agnervillafabrega-technical-test-we-imagine -Dsonar.sources=src -Dsonar.host.url=https://sonarqube.imaginamos.com -Dsonar.login=sqp_f61ea613abc37cafa41a10c0a1b82855295984cb"]


    
networks:
  sonarnet:
  
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db_data: