---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devjoss-eks
  region: us-east-1
  version: '1.27'

vpc:
  id: "vpc-03180bd3d793bc880"
  clusterEndpoints:
    publicAccess: true
  subnets:
    public:
      public-1-us-east-1a:
        id: "subnet-0ad15cce27ee520a2"
      public-2-us-east-1b:
        id: "subnet-04205c610cb733523"
      public-3-us-east-1c:
        id: "subnet-0fcb342fa61cccd5b"

managedNodeGroups:
  - name: devjoss-ng-1
    instanceType: t3.small
    privateNetworking: false
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 30
    labels: {node-group-type: managed}
    tags:
      nodegroup-role: worker