apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajvf-technical-test-deployment  # Nombre del Deployment
spec:
  replicas: 1  # Número de réplicas del pod
  selector:
    matchLabels:
      app: ajvf-technical-test  # Cambia el label de 'app' para coincidir con tu aplicación
  template:
    metadata:
      labels:
        app: ajvf-technical-test  # Asegúrate de que el label sea el mismo que en el selector
    spec:
      containers:
      - name: ajvf-technical-test-container  # Nombre del contenedor
        image: agnervillafabrega/ajvf-technical-test:latest  # Imagen que usará el contenedor
        ports:
        - containerPort: 3000  # Puerto en el que escucha la app
